---
# V2 manifest example
name: docker-registry
# replace with `bosh status --uuid`
director_uuid: cc6b3019-788f-4c32-a865-67c09d40ed9c

releases:
- name: docker-registry
  version: latest

stemcells:
- alias: trusty
  name: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw
  version: latest

# These settings are defined in cloud-config
instance_groups:
- name: docker-registry
  instances: 1
  vm_type: m1.medium
  persistent_disk_type: '102400'
  stemcell: trusty
  vm_extensions: []
  azs:
  - nova
  networks:
  - name: int-net
    default:
    - dns
    - gateway
  jobs:
  - name: registry
    release: docker-registry
  - name: proxy
    release: docker-registry
  - name: cache
    release: docker-registry
  properties:
    docker:
      cache:
        host: 127.0.0.1
        redis:
          maxmemory: "2g"
      proxy:
        auth_basic:
          jose: "{PLAIN}hola"
        ssl:
          # don't worry, this is a silly self-signed certificate, for testing
          cert: |
              -----BEGIN CERTIFICATE-----
              MIID0zCCArugAwIBAgIJAIxBsL2M4GfwMA0GCSqGSIb3DQEBCwUAMFcxCzAJBgNV
              BAYTAlNBMRUwEwYDVQQIEwxKb2hhbm5lc2J1cmcxETAPBgNVBAcTCFJhbmRidXJn
              MRIwEAYDVQQKEwlIdW50cmVjaHQxCjAIBgNVBAMUASowHhcNMTcwMTIwMjAzNjAx
              WhcNMjcwMTE4MjAzNjAxWjBXMQswCQYDVQQGEwJTQTEVMBMGA1UECBMMSm9oYW5u
              ZXNidXJnMREwDwYDVQQHEwhSYW5kYnVyZzESMBAGA1UEChMJSHVudHJlY2h0MQow
              CAYDVQQDFAEqMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzLyOYwMe
              i0qvT5FQFP9NQpDSqlyGC9ZAocQPLQJ2OdH8pRMaRjoRlZe5DFmahqWP0onHNVg3
              lAS861XxuEa+bwIRewbKkwfUIBZimIGmXt/Uo2Qwrm1rghdPt79kaTVsgqhFzfns
              VyLZhhgBYNL4M73mIDGl5vBDtCqUU716pmQGHLp+G9FWPMmJuAApnsL+x6TKzAaL
              bF0effEUV17VhAAc2sTtmLkksIzHAP0fXb17ASBmqrZb5WxrBVF6f1fhDpgOZpg5
              fMUWANMJn5+j5YrVzz2zW3Qe2ck28xquhX79IS+fq5EPXNswZ4tKlaBzyojgbEmR
              p7LZdsAhlIGSKwIDAQABo4GhMIGeMB0GA1UdDgQWBBRfUchkAsBem2Q/ht8Fd0n4
              kM78zzAfBgNVHSMEGDAWgBRfUchkAsBem2Q/ht8Fd0n4kM78zzAMBgNVHRMEBTAD
              AQH/ME4GA1UdEQRHMEWHBMCoA96CASqCAyouKoIFKi4qLiqCByouKi4qLiqCCSou
              Ki4qLiouKoILKi4qLiouKi4qLiqCDSouKi4qLiouKi4qLiowDQYJKoZIhvcNAQEL
              BQADggEBADHA4CiRZh9SDASufxansEq1brl5aucQrFVh6iiiqklLYqTIsL1RwRqN
              KFemXwh1mjONIaeZ/FWMmYe3ueuY3/pmZSMi8jN4PDUBIwV3myVKyhFALTrgWE95
              UwyMGkNxQCXzxiodKOimxkf6Z8n9K2DP6dkzmJboxxLa2ZfWHTwVvW6SWZbi+gbR
              Fq3sUrw7ZjYEEAeJagInDr3gSMqRi6kodbsKGWWTJm8cJrDjjli4M7OJB61dET5r
              FjDoNIc//DBodKKIwWM+JQlAo4DfpXyngjxr1PLMpUJPMLrhQjlLfWMxK3PDO1Vz
              b19+IEGkimvLzejPh1rDcvW1A57Cnyk=
              -----END CERTIFICATE-----
          key: |+
            -----BEGIN PRIVATE KEY-----
            MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDMvI5jAx6LSq9P
            kVAU/01CkNKqXIYL1kChxA8tAnY50fylExpGOhGVl7kMWZqGpY/Sicc1WDeUBLzr
            VfG4Rr5vAhF7BsqTB9QgFmKYgaZe39SjZDCubWuCF0+3v2RpNWyCqEXN+exXItmG
            GAFg0vgzveYgMaXm8EO0KpRTvXqmZAYcun4b0VY8yYm4ACmewv7HpMrMBotsXR59
            8RRXXtWEABzaxO2YuSSwjMcA/R9dvXsBIGaqtlvlbGsFUXp/V+EOmA5mmDl8xRYA
            0wmfn6PlitXPPbNbdB7ZyTbzGq6Ffv0hL5+rkQ9c2zBni0qVoHPKiOBsSZGnstl2
            wCGUgZIrAgMBAAECggEBAMbwPScGg+pzcq/NElSk0qzozlsNto7P7FODj/97UefT
            HDxGuJQenrGOERhoBNfrDjpU+IXkJ3UjuXKvO0aFL0vsZZH2wmZmB//54GoyKLgt
            pI/zrb3/wqRRBHwWdHoqmDrJSbLgs37j9RvwPX6Y4OZeErubooopUpBBg4lvJzt/
            XDEqyGU4WOsH7tkyI5XXWBKUovcuCBc5/GsaMqGZsbQd30WJ8hcZM+g8jVw10O8L
            3zZd62Yw0ZXKuJKVBog5YbKp7By+IGVecShva3ItdqvJK/c5bFCUaIWXqShitlaR
            ALjSyTgLPCDxRTopaWkVssTrG0XBe+FpMSDbe7GcNlECgYEA/7cwl1/UcSmxQ3rL
            7Nv0X8TaGLD6UVY+RC3fhVZ843AduVaWC+9CV5xBk+IXS7JHd6coEL5doYMl+nol
            HqLkNkMxiVtVQCcVrVhhGOJrzRJNw6seDvRD5gUNGUJ5L/IWtg3vUcOf0lpF1XH5
            OXTuEnscsxt4B4jDMf7uew/YcmkCgYEAzPbZ36i3gy9mh2Y7i/GXtCket2F0Z7Nj
            WgRWLoTzmrsm2TF4USdMUDP9aeDqhpL0o6Mtra8pJt28wHsaT/sd9M2hDF8x7KdM
            9sp59PIWIbai+c1dmMsPLECWcflQSnFeSWQ1bAI9VkFVqDoGdO1bQSKp+e2Y0HKj
            FhyAV841JXMCgYEAjSBD3/cSXtXcr9owe2s05jnVB/V8YLFRMf2DM6p0yGzS6ruf
            mbyVB5cEFiKcKrmceau2D++P6xhfOGp62/qYKl5RE3ZliT9I1l9FTx9+0TG92zQw
            JZ6nbmXxQbSO/2gDIrx0DNMC/Gu3yMHbAtvGnEp3n12Uk8vltkz0vtQS56kCgYEA
            zC6xlwyVXBtxUTs34M6Y6QH5todgFhpvw/IEBK2vnBoKtl2A1Z+Hd3KDZeGI4O0u
            xoE9dQPExBIrAbjg2oJ4MjJS2GdQ7ccwdb35RlmQUJ+HtcCvGBJZmCTzerD6Gl7b
            pdMtIN8OSYomkcLUQdFekgG9QNw/2pAJBXL5K/+hlB8CgYEAv4Qszaz1hJBE9Vs1
            RZrt3W3hbRwR/TPtdeuOxSgWhvsrDnpZQg64YAlEO3YSxvGRHAt6tWwvoZoJhjP1
            oqbK0K/bVpfnPod5cWrElaVuZ2FaJv5t/i3IsSAPl+REnpyRZkMM7E3nuLJEiyDX
            AYkmXDaI19fPkKH6U22STF19aVM=
            -----END PRIVATE KEY-----

update:
  canaries: 1
  max_in_flight: 50
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
